base_path: "/run/media/mak/OS/example_data_week5"

inputs:
    date_time:
        start: "2024-12-07 12:00:00"       # ISO format
        time_zone: "Europe/Berlin"         # Converted from CET

    paths:
        cam_path: "{base_path}/20241207_week5_cameras.txt"
        dem_path: "{base_path}/20241207_week5_dem.tif"
        orthophoto_path: "{base_path}/20241207_week5_orthophotos/*.tif"
        ori: ["{base_path}/orthophotos_5"]
        mosaic_path: "{base_path}/20241207_week5_orthomosaic.tif"
        ground_truth_coordinates: "/run/media/mak/OS/gpscoords_plots.csv"
        polygon_file_path: "{base_path}/2024_oncerco_plot_polygons.gpkg"

    settings:
        number_of_processor: -1
        filter_radius: 1
        file_name: "20241207_week5_project"
        precision: 10


outputs:
    paths:
        main_out: "{base_path}/output"
        plot_out: "{base_path}/output/plots"