# ------------------------------------------------------------------
# project configuration – WEEK 0  (12 Dec 2024 products)
# ------------------------------------------------------------------

base_path: "D:\\20240603_week0\\metashape\\20241205_products_uav_data"

inputs:
  date_time:
    start: "2024-12-12 12:00:00"          # noon on the data-stamp you processed
    time_zone: "Europe/Berlin"

  paths:
    # ► raw Metashape exports
    cam_path:         "{base_path}/20241212_week0_cameras.txt"
    dem_path:         "{base_path}/20241212_week0_dem.tif"
    orthophoto_path:  "{base_path}/20241212_week0_orthophotos/*.tif"
    ori:              ["{base_path}/20241212_week0_orthophotos"]
    mosaic_path:      "{base_path}/20241212_week0_orthomosaic.tif"   # use the newer, larger mosaic

    # ► ancillary data
    ground_truth_coordinates: "/run/media/mak/OS/gpscoords_plots.csv"
    polygon_file_path:        "{base_path}/2024_oncerco_plot_polygons.gpkg"

  settings:
    number_of_processor: -1
    filter_radius:      1
    file_name:          "20241212_week0_project"
    bands:              5
    target_crs:         "EPSG:32632"

outputs:
  paths:
    main_out: "{base_path}/output"
    plot_out: "{base_path}/output/plots"
