# ------------------------------------------------------------------
# project configuration – WEEK 5  (07 Dec 2024 base products)
# ------------------------------------------------------------------

base_path: "D:\\20240715_week5\\metashape\\20241207_week5_products_uav_data"

inputs:
  date_time:
    start: "2024-07-15 12:00:00"          # Acquisition date
    time_zone: "Europe/Berlin"

  paths:
    # ► raw Metashape exports
    cam_path:         "{base_path}/20241207_week5_cameras.txt"
    dem_path:         "{base_path}/20241207_week5_dem.tif"
    orthophoto_path:  "{base_path}/20241210_week5_orthophotos/*.tif"
    ori:              ["{base_path}/20241210_week5_orthophotos"]
    mosaic_path:      "{base_path}/20241210_week5_orthomosaic.tif"   # newer mosaic to use

    # ► ancillary data
    ground_truth_coordinates: "/run/media/mak/OS/gpscoords_plots.csv"
    polygon_file_path:        "D:\\2024_oncerco_plot_polygons.gpkg"

  settings:
    number_of_processor: -1
    filter_radius:      1
    file_name:          "20241207_week5_project"
    bands:              5
    target_crs:         "EPSG:32632"

outputs:
  paths:
    main_out: "{base_path}/output"
    plot_out: "{base_path}/output/plots"
