# ------------------------------------------------------------------
# project configuration – WEEK 8  (29 Oct 2024 base products)
# ------------------------------------------------------------------

base_path: "D:\\20240826_week8\\metashape\\20241029_products_uav_data"

inputs:
  date_time:
    start: "2024-08-26 12:00:00"          # Acquisition date (WEEK 8)
    time_zone: "Europe/Berlin"

  paths:
    # ► raw Metashape exports
    cam_path:         "{base_path}/20241029_week8_cameras.txt"
    dem_path:         "{base_path}/20241029_week8_dem.tif"
    orthophoto_path:  "{base_path}/orthophotos/*.tif"
    ori:              ["{base_path}/orthophotos"]
    mosaic_path:      "{base_path}/20241209_week8_orthomosaic.tif"   # newer/larger mosaic

    # ► ancillary data
    ground_truth_coordinates: "/run/media/mak/OS/gpscoords_plots.csv"
    polygon_file_path:        "D:\\2024_oncerco_plot_polygons.gpkg"

  settings:
    number_of_processor: -1
    filter_radius:      1
    file_name:          "20241029_week8_project"
    bands:              5
    target_crs:         "EPSG:32632"

outputs:
  paths:
    main_out: "{base_path}/output"
    plot_out: "{base_path}/output/plots"
