# ------------------------------------------------------------------
# project configuration – WEEK 1  (06 Dec 2024)
# ------------------------------------------------------------------

base_path: "D:\\20240611_week1\\metashape\\20241206_week1_products_uav_data"

inputs:
  date_time:
    start: "2024-12-06 12:00:00"          # same noon start, but on 6 Dec
    time_zone: "Europe/Berlin"

  paths:
    # ► raw Metashape products
    cam_path:          "{base_path}/20241206_week1_cameras.txt"
    dem_path:          "{base_path}/20241206_week1_dem.tif"
    orthophoto_path:   "{base_path}/orthophotos/*.tif"        # every ortho-tile in the folder
    ori:               ["{base_path}/orthophotos"]            # origin/texture tiles location
    mosaic_path:       "{base_path}/20241206_week1_orthomosaic.tif"

    # ► ancillary data
    ground_truth_coordinates: "/run/media/mak/OS/gpscoords_plots.csv"
    polygon_file_path:        "{base_path}/2024_oncerco_plot_polygons.gpkg"

  settings:
    number_of_processor: -1
    filter_radius:      1
    file_name:          "20241206_week1_project"
    bands:              5
    target_crs:         "EPSG:32632"

outputs:
  paths:
    main_out:  "{base_path}/output"
    plot_out:  "{base_path}/output/plots"
