base_path: "D:\\20241207_week5_products_uav_data"

inputs:
    date_time:
        start: "2024-12-07T10:00:00"
        time_zone: "Europe/Berlin"

    paths:
        cam_path: "{base_path}\\20241207_week5_cameras"
        dem_path: "{base_path}\\20241207_week5_dem.tif"
        orthophoto_path: "{base_path}\\20241207_week5_orthophotos\\*.tif"
        ori: ["{base_path}\\20241207_week5_orthophotos"]
        mosaic_path: "{base_path}\\20241210_week5_orthomosaic.tif"  # Picked the newer one
        ground_truth_coordinates: "D:\\Github_repository\\Example_data\\Small_dataset\\gpscoords_plots.csv"
        # polygon_file_path: "{base_path}\\optional_polygon.shp"  # Uncomment if needed

    settings:
        number_of_processor: -1
        filter_radius: 1
        file_name: "20241207_week5_project"
        precision: 4

outputs:
    paths:
        main_out: "{base_path}\\output"
